version: '2'
services:
    myhut-app:
        image: myhut
        external_links:
            - myhut-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/myhut?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myhut-mysql:
        extends:
            file: mysql.yml
            service: myhut-mysql
